version: 2.1
orbs:
  merge-configs-to-continuation: hiromishikata/merge-configs-to-continuation@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1
  node: circleci/node@5

filters: &filters
  tags:
    only: /.*/

jobs:
  command-tests:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - node/install
      - merge-configs-to-continuation/generate:
          service_directories: |
            test/service1
            test/service2/ui
            test/service2/api
      - run: cat .circleci/continuation_config.yml
workflows:
  test-deploy:
    jobs:
      - command-tests:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: hiromishikata/merge-configs-to-continuation
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
